title: "Camera2B"
description: "Berlin's Photography Adventures"
baseurl: "/camera2b" # Change if needed
#url: "https://yourdomain.com" # Update with your actual domain
theme: jekyll-theme-minimal
author: "Berlin"
show_downloads: false
